#!/usr/bin/env node
/**
 * AI-assisted test case suggestions (human-reviewed).
 * Requires OPENAI_API_KEY. Writes tests/reports/ai-test-suggestions.md
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "../..");
const outDir = path.join(root, "tests/reports");
const inventoryPath = path.join(root, "tests/utils/route-inventory.json");

const key = process.env.OPENAI_API_KEY;
if (!key) {
  console.error("OPENAI_API_KEY is required for AI-assisted suggestions.");
  process.exit(1);
}

const inventory = JSON.parse(fs.readFileSync(inventoryPath, "utf8"));
const model = process.env.TESTING_AI_MODEL || "gpt-4o-mini";

const userPrompt = `You are assisting a senior test automation architect.

Portfolio routes (JSON):
${JSON.stringify(inventory.routes, null, 2)}

Produce a markdown report with these sections:
1. Suggested additional E2E / Playwright smoke checks (bullet list, be specific to routes).
2. Suggested API / contract checks for a Secure AI Gateway (/health, error paths).
3. Content consistency checks (hero, nav labels, absence of deprecated links).
4. Edge cases worth automating (mobile nav, slow API, empty demo state).

Label the document: "AI-assisted suggestions — review before implementation."
Do not invent routes not in the inventory. Keep suggestions practical for a Next.js + FastAPI stack.`;

const res = await fetch("https://api.openai.com/v1/chat/completions", {
  method: "POST",
  headers: {
    Authorization: `Bearer ${key}`,
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    model,
    messages: [
      {
        role: "system",
        content:
          "You write concise, actionable QA suggestions in Markdown. No fluff.",
      },
      { role: "user", content: userPrompt },
    ],
    temperature: 0.4,
    max_tokens: 2_048,
  }),
});

if (!res.ok) {
  const err = await res.text();
  console.error("OpenAI API error:", res.status, err);
  process.exit(1);
}

const data = await res.json();
const text = data.choices?.[0]?.message?.content || "";
const header = `<!-- generated by npm run testing:ai:suggest | ${new Date().toISOString()} | model: ${model} -->\n\n`;

fs.mkdirSync(outDir, { recursive: true });
const mdPath = path.join(outDir, "ai-test-suggestions.md");
fs.writeFileSync(mdPath, header + text, "utf8");
console.log("Wrote", mdPath);

const jsonPath = path.join(outDir, "ai-test-suggestions-meta.json");
fs.writeFileSync(
  jsonPath,
  JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      model,
      markdownPath: "tests/reports/ai-test-suggestions.md",
    },
    null,
    2
  ),
  "utf8"
);
